#! /bin/bash
# Winbox Auto Installer
# What this script does:
#   1. Downloading wine, wget and unzip, if not installed on the system
#   2. Downloading winbox from Mikrotik's download page
#   3. Copying winbox to /usr/local/bin/ directory
#   4. Copying icons to /usr/share/icons/hicolor/*/apps
#   5. Creating launcher for Winbox
#
# Rewrite by Ariii
# version=0.10
# winbox_version=3.41

. ./modules/system.sh